version: 0.2

phases:
  install:
    commands:
      - wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
      - echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list
      - apt update
      - apt install apt-transport-https openjdk-8-jre elasticsearch-6.0.1
      - service elasticsearch start
  build:
    commands:
      - sleep 30
      - curl localhost:9200
