version: 0.2

phases:
  install:
    commands:
      - cd es
      - docker-compose build
  build:
    commands:
      - docker-compose up -d es
      - sleep 5
      - docker-compose run test python deployes/bin/deploy.py
      - docker-compose run test python -m pytest -v
