version: '2'

services:

  test:
    build: 
      context: .
      dockerfile: docker/test/Dockerfile
    environment:
      ES_HOST: es
      PYTHONPATH: /app
    links:
      - es

  es:
    build: docker/es
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - 9200:9200
