version: 0.2

phases:
  install:
    commands:
      - curl 169.254.170.2${AWS_CONTAINER_CREDENTIALS_RELATIVE_URI}
      - cd es
      - pip install -r requirements.txt
  build:
    commands:
      - PYTHONPATH=. python bin/deploy.py
